language: c

# Default linux jobs
os: linux
sudo: required
dist: trusty

# Include osx jobs
matrix:
  include:
    - os: linux
      arch: arm64
      dist: bionic
      env:
        - LABEL="arm64-gcc-lto"
    - os: linux
      arch: arm64
      dist: bionic
      addons:
      env:
        - LABEL="arm64-clang-lto"

before_install:
     - export PATH=$PATH:/usr/bin
     - cd ${TRAVIS_BUILD_DIR}
     - chmod +x ${TRAVIS_BUILD_DIR}/travis/*.sh
     - if [[ "${ENABLE_DOCKER}" == "true" ]]; then ${TRAVIS_BUILD_DIR}/travis/setupdocker.sh; fi
     - if [[ "${ENABLE_DOCKER}" == "true" ]]; then docker exec xenial /build/travis/before_install.${LABEL}.sh; fi
     - if [[ "${ENABLE_DOCKER}" != "true" ]]; then ${TRAVIS_BUILD_DIR}/travis/before_install.${LABEL}.sh; fi

before_script:
     - if [[ "${ENABLE_DOCKER}" == "true" ]]; then docker exec xenial /build/travis/before_script.${LABEL}.sh; fi
     - if [[ "${ENABLE_DOCKER}" != "true" ]]; then ${TRAVIS_BUILD_DIR}/travis/before_script.${LABEL}.sh; fi

script:
     - if [[ "${ENABLE_DOCKER}" == "true" ]]; then docker exec xenial /build/travis/script.${LABEL}.sh; fi
     - if [[ "${ENABLE_DOCKER}" != "true" ]]; then ${TRAVIS_BUILD_DIR}/travis/script.${LABEL}.sh; fi
